### ISSUE TITLE
Calendar Page / Upcoming Events widget

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#40]
Things left to complete ( @mbe5038 @nbuhay please fill in with missing things here)
- [x] URL for specific class's calendar (http://localhost/#/course/123/calendar). See `$stateProvider` states in [app.js](https://github.com/librecms/librecms/blob/master/src/angular/app/scripts/app.js#L81)
- [x] Mobile testing (See #30)
- [x] LI without UL (See #41)
- [x] API GET integration
- [x] Add upcoming events widget to homepage (See #54)
- [ ] Upcoming events widget "done" integration (See #55)

**Comment by mariusespejo** [comment]
@zdwolfe are you saying you want a separate calendar page for each class? Nick and I were originally thinking of having specific class's events be toggled to be shown or hidden using check boxes or something  (like how in google calendar you can choose to view multiple calendars on the same page). And then the upcoming events widget will be used with course pages instead of it having its own full calendar. Let me know what you think

**Comment by zdwolfe** [comment]
![make-it-so-captain](https://f.cloud.github.com/assets/719730/1455938/12fa149e-4322-11e3-9502-2f61e638d274.jpg)
